[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm build:web && pnpm build:server"

[deploy]
startCommand = "cd server && node dist/main.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
